
version: "3.9"

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - /mnt/media:/mnt/media
      - /mnt/models:/mnt/models
    depends_on:
      - mongodb
    environment:
      - UVICORN_RELOAD=true
    command: >
      uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload

  mongodb:
    image: mongo:6.0
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
