global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # EmotionalAI Application
  - job_name: 'emotionalai-app'
    static_configs:
      - targets: ['emotionalai-app:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # LLM Router
  - job_name: 'llm-router'
    static_configs:
      - targets: ['llm-router:8002']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # MongoDB
  - job_name: 'mongodb'
    static_configs:
      - targets: ['mongodb:27017']
    scrape_interval: 30s

  # Redis
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s

  # Node Exporter (if running on host)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['host.docker.internal:9100']
    scrape_interval: 30s 